name: 'Generate coverage report'

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  coverage:

    runs-on: ubuntu-latest
    name: Coverage on Ubuntu

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true
          cache: 'maven'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.5
      - name: Generate coverage with JaCoCo
        run: mvn -V --color always -ntp clean verify --file pom.xml '-Dgpg.skip'
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: 'target/site/jacoco/jacoco.xml'
          token: ${{secrets.CODECOV_TOKEN}}
